Разметка главной страницы
htmlacademy-adaptive/1975783-cat-energy-25 pull request #5
Opened 2022-04-03 20:27 UTC by Sharlize1

2022-04-04 07:11 UTC, babtshe requested changes
В целом хорошо, есть небольшие недочёты, но ничего критичного.

2022-04-04 07:11 UTC, babtshe commented on source/index.html
> +    <a class="main-header__logo-mobile" href="">
на главной атрибут href можно совсем убрать из лого.
Не нужно делать отдельные ссылки для мобильной и десктопной версии, позже мы научим лого адаптироваться. Тем более есть [критерий](https://up.htmlacademy.ru/adaptive/25/criteries#b4)

2022-04-04 07:11 UTC, babtshe commented on source/index.html
> +      <img src="img/logo-mobile.png" width="33" height="38" alt="Логотип Кэт Энерджи.">
в alt-текст не обязательно ставить точки, но это не ошибка

2022-04-04 07:11 UTC, babtshe commented on source/index.html
> +            <a class="site-list__link" href="">
ссылки на остальные странице было бы хорошо поставить

2022-04-04 07:11 UTC, babtshe commented on source/index.html
> +      <div class="select-programm__wrapper">
на этапе разметки лучше не увлекаться лишними обёртками, их всегда можно добавить в случае необходимости потом.

2022-04-04 07:11 UTC, babtshe commented on source/index.html
> +    </ul>
логотип и подпись к нему - точно не отдельные элементы списка, здесь стоит немного подумать как переделать.

2022-04-05 08:22 UTC, Sharlize1 commented on source/index.html
> +    <a class="main-header__logo-mobile" href="">
href убрала

2022-04-05 08:31 UTC, Sharlize1 commented on source/index.html
> +      <img src="img/logo-mobile.png" width="33" height="38" alt="Логотип Кэт Энерджи.">
удалила точки, 
но на прошлой защите мне не зачли вот такой критерий из-за точек
![image](https://user-images.githubusercontent.com/95186720/161712253-631bcd4f-d41b-4552-8502-59d76d83ff17.png)

2022-04-05 08:35 UTC, Sharlize1 commented on source/index.html
> +            <a class="site-list__link" href="">
ссылки добавлены
![image](https://user-images.githubusercontent.com/95186720/161713157-4678fbaf-f39f-430a-b12a-31aed6037ddb.png)

2022-04-05 09:30 UTC, Sharlize1 commented on source/index.html
> +      <div class="select-programm__wrapper">
wrapper-ы убрала, 
но так показывали на лайве)

2022-04-05 09:45 UTC, Sharlize1 commented on source/index.html
> +    </ul>
Переделала
![image](https://user-images.githubusercontent.com/95186720/161726858-d01eccb4-2075-41ce-b242-bc7b390ebae1.png)

2022-04-06 07:16 UTC, babtshe commented on source/index.html
> +      <img src="img/logo-mobile.png" width="33" height="38" alt="Логотип Кэт Энерджи.">
В таких случаях хорошо смотреть в [документацию](https://webaim.org/techniques/alttext/). Знаки препинания пригодятся, если описание состоит из нескольких предложений.

2022-04-06 07:18 UTC, babtshe commented on source/index.html
> +      <div class="select-programm__wrapper">
Нужно понимать какую задачу решают эти обёртки. Если никакой практической ценности они не несут, то добавлять только потому что сказали на лекции - не стоит.

2022-04-06 07:21 UTC, babtshe approved these changes

2022-04-06 07:21 UTC, merged