Разметка внутренних страниц
htmlacademy-adaptive/1975783-cat-energy-25 pull request #6
Opened 2022-04-04 09:34 UTC by Sharlize1

2022-04-07 07:19 UTC, babtshe requested changes
<img width="941" alt="image" src="https://user-images.githubusercontent.com/30229773/162142066-9b365552-2126-4575-bfbc-ba10fe3305b2.png">
Видимо забыла синхронизировать мастер, хорошо бы поправить.

2022-04-07 07:19 UTC, babtshe commented on source/catalog.html
> +            <button class="product-card__button button" type="button">Заказать</button>
лучше делать ссылкой, тогда у пользователя будет возможность заказать, даже если скрипты сломаются.

2022-04-07 07:19 UTC, babtshe commented on source/catalog.html
> +            <button class="additional-catalog__button button" type="button">Заказать</button>
❗️

2022-04-07 07:19 UTC, babtshe commented on source/catalog.html
> +    </section>
скорее всего для вёрстки будет удобнее закинуть в список товаров, но к этому можно позже вернуться.

2022-04-07 07:19 UTC, babtshe commented on source/form.html
> +                <input class="programm-form__checkbox" type="checkbox" name="sweetener" id="sweetener"
есть смысл задать чекбоксам одинаковое имя, но разные значения, тогда при отправке на сервер будет приходить аккуратный массив с результатами выбора.

2022-04-07 10:38 UTC, Sharlize1 commented on source/catalog.html
> +            <button class="product-card__button button" type="button">Заказать</button>
переделала баттоны в карточках товаров на ссылки

2022-04-07 10:38 UTC, Sharlize1 commented on source/catalog.html
> +            <button class="additional-catalog__button button" type="button">Заказать</button>
переделано на ссылки

2022-04-07 10:40 UTC, Sharlize1 commented on source/catalog.html
> +    </section>
возьму на контроль, вернемся позже

2022-04-07 11:18 UTC, Sharlize1 commented on source/form.html
> +                <input class="programm-form__checkbox" type="checkbox" name="sweetener" id="sweetener"
сделала одно значение name и разные value
![image](https://user-images.githubusercontent.com/95186720/162187207-ace1f0e5-a4bc-46b5-a0f6-563a2703b866.png)

2022-04-07 11:33 UTC, Sharlize1 commented
Синхронизацию сделала

2022-04-08 08:22 UTC, babtshe requested changes
Правки - ок. 
Синхронизация не сработала:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/30229773/162395082-f8c0f39c-6cf3-4c72-88b5-03661fb3bbc7.png">
Рабочая ветка не должна быть позади мастера.
Тут видно, что в рабочей ветке нет изменений с последними правками главной:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/30229773/162395757-15527b54-769c-4527-b91b-f321c964ad41.png">

2022-04-08 13:12 UTC, closed without merging